global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # ZAMC Web Frontend
  - job_name: 'zamc-web'
    static_configs:
      - targets: ['zamc-web:3000']
    metrics_path: '/health'
    scrape_interval: 30s

  # ZAMC BFF GraphQL API
  - job_name: 'zamc-bff'
    static_configs:
      - targets: ['zamc-bff:4000']
    metrics_path: '/metrics'
    scrape_interval: 15s

  # ZAMC Orchestrator Service
  - job_name: 'zamc-orchestrator'
    static_configs:
      - targets: ['zamc-orchestrator:8001']
    metrics_path: '/metrics'
    scrape_interval: 15s

  # ZAMC Connectors Service
  - job_name: 'zamc-connectors'
    static_configs:
      - targets: ['zamc-connectors:8002']
    metrics_path: '/metrics'
    scrape_interval: 15s

  # PostgreSQL Database
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres:5432']
    scrape_interval: 30s

  # Redis Cache
  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']
    scrape_interval: 30s

  # NATS Message Broker
  - job_name: 'nats'
    static_configs:
      - targets: ['nats:8222']
    metrics_path: '/metrics'
    scrape_interval: 15s

  # Node Exporter (if added)
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 30s

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093 