{{- if and .Values.bff.enabled .Values.bff.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "zamc.fullname" . }}-bff
  labels:
    {{- include "zamc.labels" . | nindent 4 }}
    app.kubernetes.io/component: bff
  {{- with .Values.bff.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.bff.ingress.className }}
  ingressClassName: {{ .Values.bff.ingress.className }}
  {{- end }}
  {{- if .Values.bff.ingress.tls }}
  tls:
    {{- range .Values.bff.ingress.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
    {{- range .Values.bff.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path }}
            {{- if .pathType }}
            pathType: {{ .pathType }}
            {{- end }}
            backend:
              service:
                name: {{ include "zamc.fullname" $ }}-bff
                port:
                  number: {{ $.Values.bff.service.port }}
          {{- end }}
    {{- end }}
{{- end }} 