{{- if .Values.bff.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "zamc.fullname" . }}-bff
  labels:
    {{- include "zamc.labels" . | nindent 4 }}
    app.kubernetes.io/component: bff
spec:
  type: {{ .Values.bff.service.type }}
  ports:
    - port: {{ .Values.bff.service.port }}
      targetPort: {{ .Values.bff.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "zamc.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: bff
{{- end }} 