{{- if .Values.monitoring.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: {{ include "zamc.fullname" . }}-security-alerts
  labels:
    {{- include "zamc.labels" . | nindent 4 }}
    prometheus: security
spec:
  groups:
    - name: zamc.security.critical
      interval: 30s
      rules:
        # Critical Security Events
        - alert: CriticalSecurityEvent
          expr: increase(security_events_total{severity="critical"}[5m]) > 0
          for: 0s
          labels:
            severity: critical
            category: security
          annotations:
            summary: "Critical security event detected"
            description: "A critical security event has been detected in {{ $labels.service }}. Event type: {{ $labels.event_type }}"
            runbook_url: "https://docs.zamc.com/runbooks/security/critical-events"

        # Authentication Failures
        - alert: HighAuthenticationFailureRate
          expr: rate(failed_auth_total[5m]) > 0.1
          for: 2m
          labels:
            severity: warning
            category: authentication
          annotations:
            summary: "High authentication failure rate detected"
            description: "Authentication failure rate is {{ $value }} failures/sec, above threshold of 0.1/sec"
            runbook_url: "https://docs.zamc.com/runbooks/security/auth-failures"

        - alert: SuspiciousAuthenticationActivity
          expr: increase(failed_auth_total[10m]) > 20
          for: 1m
          labels:
            severity: critical
            category: authentication
          annotations:
            summary: "Suspicious authentication activity detected"
            description: "{{ $value }} failed authentication attempts in the last 10 minutes"
            runbook_url: "https://docs.zamc.com/runbooks/security/suspicious-auth"

        # Brute Force Detection
        - alert: BruteForceAttack
          expr: increase(failed_auth_total{source_ip!=""}[5m]) by (source_ip) > 10
          for: 30s
          labels:
            severity: critical
            category: attack
          annotations:
            summary: "Brute force attack detected"
            description: "IP {{ $labels.source_ip }} has {{ $value }} failed authentication attempts in 5 minutes"
            runbook_url: "https://docs.zamc.com/runbooks/security/brute-force"

    - name: zamc.security.injection
      interval: 30s
      rules:
        # SQL Injection Attempts
        - alert: SQLInjectionAttempt
          expr: increase(security_events_total{event_type="sql_injection"}[5m]) > 0
          for: 0s
          labels:
            severity: critical
            category: injection
          annotations:
            summary: "SQL injection attempt detected"
            description: "SQL injection attempt detected from {{ $labels.source_ip }} on {{ $labels.service }}"
            runbook_url: "https://docs.zamc.com/runbooks/security/sql-injection"

        # XSS Attempts
        - alert: XSSAttempt
          expr: increase(security_events_total{event_type="xss"}[5m]) > 0
          for: 0s
          labels:
            severity: high
            category: injection
          annotations:
            summary: "XSS attempt detected"
            description: "Cross-site scripting attempt detected from {{ $labels.source_ip }}"
            runbook_url: "https://docs.zamc.com/runbooks/security/xss-attempt"

        # Command Injection
        - alert: CommandInjectionAttempt
          expr: increase(security_events_total{event_type="command_injection"}[5m]) > 0
          for: 0s
          labels:
            severity: critical
            category: injection
          annotations:
            summary: "Command injection attempt detected"
            description: "Command injection attempt detected on {{ $labels.service }}"
            runbook_url: "https://docs.zamc.com/runbooks/security/command-injection"

    - name: zamc.security.access
      interval: 30s
      rules:
        # Privilege Escalation
        - alert: PrivilegeEscalationAttempt
          expr: increase(security_events_total{event_type="privilege_escalation"}[5m]) > 0
          for: 0s
          labels:
            severity: critical
            category: access
          annotations:
            summary: "Privilege escalation attempt detected"
            description: "Privilege escalation attempt by user {{ $labels.user_id }} on {{ $labels.service }}"
            runbook_url: "https://docs.zamc.com/runbooks/security/privilege-escalation"

        # Unauthorized Access
        - alert: UnauthorizedAccessAttempt
          expr: increase(security_events_total{event_type="unauthorized_access"}[5m]) > 0
          for: 0s
          labels:
            severity: high
            category: access
          annotations:
            summary: "Unauthorized access attempt"
            description: "Unauthorized access attempt to {{ $labels.resource }} by {{ $labels.user_id }}"
            runbook_url: "https://docs.zamc.com/runbooks/security/unauthorized-access"

        # Admin Panel Access
        - alert: AdminPanelAccess
          expr: increase(admin_access_total[5m]) > 0
          for: 0s
          labels:
            severity: warning
            category: access
          annotations:
            summary: "Admin panel access detected"
            description: "Admin panel accessed by {{ $labels.user_id }} from {{ $labels.source_ip }}"
            runbook_url: "https://docs.zamc.com/runbooks/security/admin-access"

    - name: zamc.security.network
      interval: 30s
      rules:
        # Suspicious Network Activity
        - alert: SuspiciousNetworkActivity
          expr: rate(http_requests_total{status=~"4[0-9][0-9]"}[5m]) by (source_ip) > 10
          for: 2m
          labels:
            severity: warning
            category: network
          annotations:
            summary: "Suspicious network activity detected"
            description: "High rate of 4xx errors from IP {{ $labels.source_ip }}: {{ $value }} requests/sec"
            runbook_url: "https://docs.zamc.com/runbooks/security/suspicious-network"

        # DDoS Detection
        - alert: PossibleDDoSAttack
          expr: rate(http_requests_total[1m]) > 1000
          for: 30s
          labels:
            severity: critical
            category: attack
          annotations:
            summary: "Possible DDoS attack detected"
            description: "Request rate is {{ $value }} requests/sec, above normal threshold"
            runbook_url: "https://docs.zamc.com/runbooks/security/ddos-attack"

        # Rate Limit Violations
        - alert: RateLimitViolations
          expr: increase(rate_limit_violations_total[5m]) > 100
          for: 1m
          labels:
            severity: warning
            category: rate_limit
          annotations:
            summary: "High rate of rate limit violations"
            description: "{{ $value }} rate limit violations in the last 5 minutes"
            runbook_url: "https://docs.zamc.com/runbooks/security/rate-limits"

    - name: zamc.security.data
      interval: 30s
      rules:
        # Data Exfiltration
        - alert: SuspiciousDataExfiltration
          expr: rate(api_data_exported_bytes[5m]) > 100000000  # 100MB/5min
          for: 2m
          labels:
            severity: critical
            category: data
          annotations:
            summary: "Suspicious data exfiltration detected"
            description: "Large amount of data exported: {{ $value }} bytes/sec"
            runbook_url: "https://docs.zamc.com/runbooks/security/data-exfiltration"

        # Sensitive Data Access
        - alert: SensitiveDataAccess
          expr: increase(sensitive_data_access_total[5m]) > 0
          for: 0s
          labels:
            severity: high
            category: data
          annotations:
            summary: "Sensitive data access detected"
            description: "Access to sensitive data by {{ $labels.user_id }} for {{ $labels.data_type }}"
            runbook_url: "https://docs.zamc.com/runbooks/security/sensitive-data"

    - name: zamc.security.infrastructure
      interval: 60s
      rules:
        # Container Security Violations
        - alert: ContainerSecurityViolation
          expr: increase(container_security_violations_total[5m]) > 0
          for: 0s
          labels:
            severity: critical
            category: infrastructure
          annotations:
            summary: "Container security violation detected"
            description: "Security violation in container {{ $labels.container }} on {{ $labels.pod }}"
            runbook_url: "https://docs.zamc.com/runbooks/security/container-violations"

        # Pod Security Policy Violations
        - alert: PodSecurityPolicyViolation
          expr: increase(pod_security_policy_violations_total[5m]) > 0
          for: 0s
          labels:
            severity: high
            category: infrastructure
          annotations:
            summary: "Pod security policy violation"
            description: "Pod security policy violation in {{ $labels.namespace }}/{{ $labels.pod }}"
            runbook_url: "https://docs.zamc.com/runbooks/security/pod-security"

        # Network Policy Violations
        - alert: NetworkPolicyViolation
          expr: increase(network_policy_violations_total[5m]) > 0
          for: 0s
          labels:
            severity: high
            category: infrastructure
          annotations:
            summary: "Network policy violation"
            description: "Network communication blocked by policy in {{ $labels.namespace }}"
            runbook_url: "https://docs.zamc.com/runbooks/security/network-policy"

        # Certificate Expiration
        - alert: CertificateExpirationWarning
          expr: (cert_expiry_timestamp - time()) / 86400 < 30
          for: 5m
          labels:
            severity: warning
            category: infrastructure
          annotations:
            summary: "Certificate expiring soon"
            description: "Certificate {{ $labels.cert_name }} expires in {{ $value }} days"
            runbook_url: "https://docs.zamc.com/runbooks/security/cert-expiration"

        - alert: CertificateExpirationCritical
          expr: (cert_expiry_timestamp - time()) / 86400 < 7
          for: 1m
          labels:
            severity: critical
            category: infrastructure
          annotations:
            summary: "Certificate expiring very soon"
            description: "Certificate {{ $labels.cert_name }} expires in {{ $value }} days"
            runbook_url: "https://docs.zamc.com/runbooks/security/cert-expiration"

    - name: zamc.security.compliance
      interval: 300s  # 5 minutes
      rules:
        # Security Event Aggregation
        - alert: SecurityEventThreshold
          expr: increase(security_events_total[1h]) > 100
          for: 5m
          labels:
            severity: warning
            category: compliance
          annotations:
            summary: "High security event volume"
            description: "{{ $value }} security events in the last hour"
            runbook_url: "https://docs.zamc.com/runbooks/security/event-threshold"

        # Failed Security Scans
        - alert: SecurityScanFailure
          expr: security_scan_success == 0
          for: 5m
          labels:
            severity: high
            category: compliance
          annotations:
            summary: "Security scan failure"
            description: "Security scan failed for {{ $labels.scan_type }} on {{ $labels.target }}"
            runbook_url: "https://docs.zamc.com/runbooks/security/scan-failure"

        # Vulnerability Detection
        - alert: HighSeverityVulnerability
          expr: vulnerability_count{severity="critical"} > 0
          for: 0s
          labels:
            severity: critical
            category: compliance
          annotations:
            summary: "Critical vulnerability detected"
            description: "{{ $value }} critical vulnerabilities found in {{ $labels.component }}"
            runbook_url: "https://docs.zamc.com/runbooks/security/vulnerabilities"

        - alert: SecurityPolicyViolation
          expr: increase(policy_violations_total[5m]) > 0
          for: 0s
          labels:
            severity: high
            category: compliance
          annotations:
            summary: "Security policy violation"
            description: "Security policy violation: {{ $labels.policy_name }} in {{ $labels.service }}"
            runbook_url: "https://docs.zamc.com/runbooks/security/policy-violations"

{{- end }} 