{{- if .Values.podSecurityPolicy.enabled }}
apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: {{ include "zamc.fullname" . }}-restricted
  labels:
    {{- include "zamc.labels" . | nindent 4 }}
spec:
  # Privilege and access controls
  privileged: false
  allowPrivilegeEscalation: false
  requiredDropCapabilities:
    - ALL
  allowedCapabilities: []
  
  # Host access controls
  hostNetwork: false
  hostIPC: false
  hostPID: false
  hostPorts: []
  
  # Volume controls
  volumes:
    - 'configMap'
    - 'emptyDir'
    - 'projected'
    - 'secret'
    - 'downwardAPI'
    - 'persistentVolumeClaim'
  allowedHostPaths: []
  
  # Run as controls
  runAsUser:
    rule: 'MustRunAsNonRoot'
  runAsGroup:
    rule: 'MustRunAs'
    ranges:
      - min: 1
        max: 65535
  supplementalGroups:
    rule: 'MustRunAs'
    ranges:
      - min: 1
        max: 65535
  fsGroup:
    rule: 'MustRunAs'
    ranges:
      - min: 1
        max: 65535
  
  # Security profiles
  seLinux:
    rule: 'RunAsAny'
  seccompProfile:
    type: 'RuntimeDefault'
  
  # Read-only root filesystem
  readOnlyRootFilesystem: true
  
  # Forbidden sysctls
  forbiddenSysctls:
    - '*'
  
  # Default security context
  defaultAddCapabilities: []
  defaultAllowPrivilegeEscalation: false

---
# RBAC for Pod Security Policy
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "zamc.fullname" . }}-psp-restricted
  labels:
    {{- include "zamc.labels" . | nindent 4 }}
rules:
  - apiGroups:
      - policy
    resources:
      - podsecuritypolicies
    verbs:
      - use
    resourceNames:
      - {{ include "zamc.fullname" . }}-restricted

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "zamc.fullname" . }}-psp-restricted
  labels:
    {{- include "zamc.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "zamc.fullname" . }}-psp-restricted
subjects:
  - kind: ServiceAccount
    name: {{ include "zamc.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}

{{- end }} 