apiVersion: v1
kind: Secret
metadata:
  name: {{ include "zamc.fullname" . }}-secrets
  labels:
    {{- include "zamc.labels" . | nindent 4 }}
type: Opaque
data:
  # Database configuration
  database-url: {{ include "zamc.databaseUrl" . | b64enc | quote }}
  
  # Redis configuration
  redis-url: {{ include "zamc.redisUrl" . | b64enc | quote }}
  
  # NATS configuration
  nats-url: {{ include "zamc.natsUrl" . | b64enc | quote }}
  
  # JWT configuration
  jwt-secret: {{ .Values.secrets.jwt.secret | b64enc | quote }}
  
  # AI API keys
  openai-api-key: {{ .Values.secrets.ai.openaiApiKey | b64enc | quote }}
  anthropic-api-key: {{ .Values.secrets.ai.anthropicApiKey | b64enc | quote }}
  huggingface-api-key: {{ .Values.secrets.ai.huggingfaceApiKey | b64enc | quote }}
  
  # Google Ads configuration
  google-ads-developer-token: {{ .Values.secrets.googleAds.developerToken | b64enc | quote }}
  google-ads-client-id: {{ .Values.secrets.googleAds.clientId | b64enc | quote }}
  google-ads-client-secret: {{ .Values.secrets.googleAds.clientSecret | b64enc | quote }}
  google-ads-refresh-token: {{ .Values.secrets.googleAds.refreshToken | b64enc | quote }}
  google-ads-customer-id: {{ .Values.secrets.googleAds.customerId | b64enc | quote }}
  google-ads-login-customer-id: {{ .Values.secrets.googleAds.loginCustomerId | b64enc | quote }}
  
  # Meta configuration
  meta-app-id: {{ .Values.secrets.meta.appId | b64enc | quote }}
  meta-app-secret: {{ .Values.secrets.meta.appSecret | b64enc | quote }}
  meta-access-token: {{ .Values.secrets.meta.accessToken | b64enc | quote }}
  meta-ad-account-id: {{ .Values.secrets.meta.adAccountId | b64enc | quote }}
  meta-api-version: {{ .Values.secrets.meta.apiVersion | b64enc | quote }}
  
  # Supabase configuration (if used)
  supabase-url: {{ .Values.secrets.supabase.url | default "" | b64enc | quote }}
  supabase-anon-key: {{ .Values.secrets.supabase.anonKey | default "" | b64enc | quote }} 