apiVersion: v2
name: zamc
description: ZAMC - AI-Powered Marketing Campaign Platform
type: application
version: 1.0.0
appVersion: "1.0.0"
home: https://github.com/zamc/zamc-v2
sources:
  - https://github.com/zamc/zamc-v2
maintainers:
  - name: ZAMC Team
    email: team@zamc.dev
keywords:
  - marketing
  - ai
  - campaigns
  - automation
dependencies:
  - name: postgresql
    version: 12.x.x
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
  - name: redis
    version: 17.x.x
    repository: https://charts.bitnami.com/bitnami
    condition: redis.enabled
  - name: nats
    version: 0.19.x
    repository: https://nats-io.github.io/k8s/helm/charts/
    condition: nats.enabled 