// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zklzwarmswkakaeglpdi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InprbHp3YXJtc3drYWthZWdscGRpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc5NzYyOTcsImV4cCI6MjA2MzU1MjI5N30.CY7gaFldCuro-WN5kd7MPSrtaT_uCSKlMUrwjaGXs_I";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);