
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "zamc-web.fullname" . }}-config
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "zamc-web.labels" . | nindent 4 }}
data:
  VITE_APP_ENV: {{ .Values.env | get "VITE_APP_ENV" | default "production" | quote }}
